### ISSUE TITLE
No offset commit example

### ISSUE THREAD

**Issue by ns-shua** [googleapis/java-pubsublite#1189]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
I don't see any example of commit a subscribtion offset

**Comment by dpcollins-google** [comment]
We will likely not expose manual offset commits. The preferred use case for Pub/Sub Lite clients is via the Cloud Pub/Sub shim APIs, not through the underlying wire protocols. The shim API abstracts away from needing to care about offset commits.
