### ISSUE TITLE
Better exception for AdminClient

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/java-pubsublite#148]
The exception that needs handling from the autocloseable `try(AdminClient adminClient = AdminClient.create(adminClientSettings)` is `java.lang.Exception`, which is very generic.

Pub/Sub uses `java.io.IOException` for `TopicAdminClient` and `SubscriptionAdminClient` ([samples](https://github.com/googleapis/java-pubsub/tree/master/samples/snippets/src/main/java/pubsub)).

See original [comment](https://github.com/googleapis/java-pubsublite/pull/147#discussion_r444510854) by @kurtisvg.

**Comment by lesv** [comment]
Does pubsub just throw IOException?  That is better than just Exception.  Better still is a more specific exception

**Comment by lesv** [comment]
Looking at the code, I see `io.grpc.StatusException` which is more specific and the user can actually check it's contents to figure out what's going on.

**Comment by lesv** [comment]
[`io.grpc.StatusException`](https://grpc.github.io/grpc-java/javadoc/io/grpc/StatusException.html) has a `getStatus` method which returns an [`io.grpc.status`](https://grpc.github.io/grpc-java/javadoc/io/grpc/Status.html) which has lots of additional info as well as `metadata` trailers.  Much better for the user.

**Comment by anguillanneuf** [comment]
`io.grpc.StatusException` is indeed thrown by AdminClient creation (`AdminClient.create(adminClientSettings)`). And `java.lang.InterruptedException` and `java.util.concurrent.ExecutionException` are thrown by the `.get()` method. 
But the try with resources block throws `java.lang.Exception`.

**Comment by kurtisvg** [comment]
@anguillanneuf A try-with-resources doesn't throw any exception, only the functions used within it do. Is this actually a client bug or do we just need to update the samples?

**Comment by anguillanneuf** [comment]
@kurtisvg It is the client. Without throwing `java.lang.Exception`, I get:

```
[ERROR] /Users/.../Projects/java-pubsublite/samples/snippets/src/main/java/pubsublite/CreateTopicExample.java:[83,22] unreported exception java.lang.Exception; must be caught or declared to be thrown
  exception thrown from implicit call to close() on resource variable 'adminClient'
```

With this function signature:

```java
  public static void createTopicExample(
      String cloudRegion, char zoneId, long projectNumber, String topicId, int partitions)
      throws StatusException, ExecutionException, InterruptedException {
  // ...
  }
```

**Comment by kurtisvg** [comment]
@anguillanneuf My apologies you are correct - I was looking at the java-pubsub samples linked above not realizing they weren't java-pubsublite. 

Digging deeper, it looks like this issue may be bigger than just an over-generic exception. The `AutoClosable` interface provides a `close()` method which is scoped to `Exception`. In Java/pubsub the `AdminClient` overrides this: https://github.com/googleapis/java-pubsub/blob/9c750c8e4899ae994a788c5323fc456ac5d7aa38/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java#L1471-L1474

Looking at the pubsub-lite `AdminClient` interface, it looks like not only is the `close()` operation not overrode, but checking out `AdminClientImpl` it doesn't even look implemented: https://github.com/googleapis/java-pubsublite/blob/master/google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AdminClientImpl.java

**Comment by hannahrogers-google** [comment]
I don't think there is much we can do in the pubsublite client library to fix this at the moment. The Autocloseable 'close' method is implemented by com.google.api.gax.core.BackendResourceAggregation (AdminClientImpl extends BackendResourceAggregation) - the close method in BackendResourceAggregation throws the generic exception.

It does look like gax plans to remove the Exception in the next major version, so we can resolve this issue then: https://github.com/googleapis/gax-java/blob/master/gax/src/main/java/com/google/api/gax/core/BackgroundResourceAggregation.java#L90

**Comment by anguillanneuf** [comment]
I see. So in Pub/Sub, both [`TopicAdminClient`](https://github.com/googleapis/java-pubsub/blob/9c750c8e4899ae994a788c5323fc456ac5d7aa38/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java#L133) and [`SubscriptionAdminClient`](https://github.com/googleapis/java-pubsub/blob/bd85b3958381abc5307cf4ddab5c80f360893538/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java#L146) implement `BackgroundResource`. But in Pub/Sub Lite, `AdminClientImpl` extends `BackgroundReourceAggregate`:

https://github.com/googleapis/java-pubsublite/blob/3c471abd2f0437a249e3bf631b6351f2bf693666/google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AdminClientImpl.java#L63

Unless we change `AdminClientImpl` to implement `BackgroundReource`, we will have to wait for the next major update for `BackgroundReourceAggregate`. 

The question is when their next major update will be and whether it will be sooner or later than our GA. If later, we probably need to do what Pub/Sub does or discuss alternatives.

**Comment by hannahrogers-google** [comment]
Yes, exactly - I will reach out to the gax team to see if there is any timeline for a major release.  If not, I can make the changes to our AdminClient to no longer use BackgroundResourceAggregate.
