### ISSUE TITLE
Support per partition MessageReceiver

### ISSUE THREAD

**Issue by gpoulin** [googleapis/java-pubsublite#471]
**Is your feature request related to a problem? Please describe.**
There's currently no easy way to know from which partition a message come from while using the `Subscriber` interface. This prevent to implement more complex control flow on a per partition basis. e.g.: We might want to stop processing new messages if there's a single outstanding message with an offset smaller than current offset minus X. In addition, there's no way to determine a unique id as only the offset is available. Ideally the publisher should include an id as an attribute, but there's use case where distinguishing between a message that have been publish more than once vs a message that have been deliver more than once can be useful.

**Describe the solution you'd like**
Modify `SubcriberSettings.Builder` to add the method `setReceiverFactory(ApiFunction<Partition, MessageReceiver> receiverFactory)`. The method `setReceiver(MessageReceiver receiver)` should simply call this method, ignoring the `Partition` parameter.

**Describe alternatives you've considered**

Using `AssigningSubscriber` by giving `PartitionSubscriberFactory` that simply build a `Subscriber` from a `SubcriberSettings` where `partitions` have been set to a list of one element. Those are in the `com.google.cloud.pubsublite.cloudpubsub.internal` so it doesn't seem to be something that should be used outside the library.

**Comment by dpcollins-google** [comment]
Hi Guillame,

I have no issue exposing the partition in the interface, although I would do it in a slightly different way than you've described, by putting it on a well-known attribute. However, I want to understand your use case better: are you saying you want to implement additional flow control on top of the existing logic? What scenario are you attempting to handle.

> if there's a single outstanding message with an offset smaller than current offset minus X

This section worries me because Pub/Sub Lite offsets are not guaranteed to be consecutive within partitions. Perhaps you can expand more on the specific behavior you're trying to implement so I can see if there's a better way to approach it?

-Dan

**Comment by gpoulin** [comment]
Our current Kafka consumers process message in batch per partition. They don't process the next batch until the offset of the current batch have been committed. It looks a little like:

```scala
def process(partition: Long, processor: Seq[Message] => Future[Unit]): Future[Unit] = {
  def go(messages: Seq[Message], cursor: Cursor): Future[Unit] = {
    val next = fetchMessage(cursor)
    for {
      _ <- processor(messages)
      _ <- commitCursor(cursor)
     (nexMessages, nextCursor) <-  next
     _ <- go(nextMessages, nextCursor)
    } yield ()
  }

  for {
    currentCursor <- getCurrentCursor(partition)
    (message, nextCursor) <- fetchMessages(currentCursor)
    _ <- go(message, nextCursor)
  } yield () 
}

```

To reproduce this behaviour, we can simply buffer messages within the `MessageReceiver`.  After x seconds or when buffer reach a certain size, we can call the `processor` function making sure that the future returned by the previous call have been fulfilled first. However, since there's a single `MessageReceiver` share by all partitions, the buffering queue would also be share across all partitions. However, if we have a `MessageReceiver` per partition or if we can know the partition a message come from, we can reproduce this behaviour. (It wouldn't be strictly the same because `AckReplyConsumer` doesn't return an `ApiFuture` so we can't wait for the offset to be committed).

I think we will want to relax a little the processing ordering for new consumer and simply do ordering per key which the java client allow to do. However, there's a risk that consumer continue processing messages without ever committing offset if a single message is never `ack` or `nack`. If we know the partition of messages or if we have a `MessageReceiver` per partition, we can detect this situation and stop processing further messages.

**Comment by dpcollins-google** [comment]
Pub/Sub Lite exposes multiple models for interaction. One of those is the kafka consumer API available at https://github.com/googleapis/java-pubsublite-kafka. Might it be lower impedance to use that model?

> process message in batch per partition

Do you use assign() with the kafka consumer, not subscribe()? I'm familiar with the kafka APIs so it would be better to deal in the exact loop within those APIs you call. If so, the equivalent in this library would be to create multiple subscribers with specifically set partitions https://github.com/googleapis/java-pubsublite/blob/425983545bb4d8ac526296a6db2e6aac4c17a512/google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java#L156

> They don't process the next batch until the offset of the current batch have been committed

I'm reading that you use autocommit from this? What I would suggest you do is just have a wrapper around your existing process behavior that does:

```
void processMessage(PubsubMessage message, AckReplyConsumer ackConsumer) {
  processor.apply(ImmutableList.of(message));
  ackConsumer.ack();
}
```

Unless it is important that your code handle batches for some reason?

> there's a risk that consumer continue processing messages without ever committing offset if a single message is never ack or nack

This seems like the code would be incorrect then- if it never acknowledges successful completion of message processing, you have a bug, which should be rare. You can detect this using cloud monitoring metrics indicating that subscription backlog is growing.

> ack or nack

Note that nack is not supported by default: You need to specifically install a NackHandler to handle when nack() is called, which must unconditionally acknowledge the message after performing intermediate processing.

Also feel free to reach out to me through email if you want to have a discussion about how we can best support your use case.
