### ISSUE TITLE
Make it easier to use non defaults CredentialsProvider

### ISSUE THREAD

**Issue by gpoulin** [googleapis/java-pubsublite#472]
**Is your feature request related to a problem? Please describe.**
To be able to set a CredentialsProvider on a SubscriberSettings, you need to set the credentials on a `Supplier<SubscriberServiceClient>`, a `Supplier<CursorServiceClient>`  and a `PartitionAssignmentServiceClient`

**Describe the solution you'd like**
Be able to set `CredentialsProvider` on the `SubscriberSettings` directly.

**Comment by dpcollins-google** [comment]
Hi Guillaume,

Trying to figure out how to prioritize this: Are you unable to use default credentials either through GOOGLE_APPLICATION_CREDENTIALS or machine defaults on Compute Engine? If so, why? If we implemented this, we'd probably want to do it across other languages as well.

-Dan

**Comment by gpoulin** [comment]
Do facilitate our migration to GCP, we will need to be able to publish messages to Pub/Sub from our data center. In our infrastructure, the local filesystem can't be considered secure . For other GCP client, we simply base64 the credential file and put he result as an environment variable. Creating a CredentialsProvider from that is pretty trivial.

In addition, we have used impersonated credentials from time to time.

**Comment by dpcollins-google** [comment]
Thank you for the scope as to why this is necessary. I'll ensure this is implemented in all clients.
