### ISSUE TITLE
Publisher sample doesn't exit, why?

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/java-pubsublite#481]
How to reproduce:

1. Go to `samples/snippets/src/main/java/pubsublite/PublisherExample.java` and completes TODO(developer).

2. Run the publisher example. Messages are published, the publisher terminates, but the program doesn't exit. 
```sh
cd samples/snippets/
mvn compile exec:java -Dexec.mainClass=pubsublite.PublisherExample
```

I tried setting `-Dexec.cleanupDaemonThreads` to `False` and `True` but neither seemed to help.

**Comment by dpcollins-google** [comment]
This is fixed in the most recent build- executors needed to be marked as daemon threads.
