### ISSUE TITLE
PubSub Lite DataFlow Errors - ManagedChannelImpl was not shutdown properly

### ISSUE THREAD

**Issue by GLStephen** [googleapis/java-pubsublite#548]
When running PubSubLite as a subscriber in a dataflow job I'm receiving the following error repeatedly.

```
"*~*~*~ Channel ManagedChannelImpl{logId=845, target=us-east1-pubsublite.googleapis.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true."
```

The connection is handled in the Pipeline. Do I need to get a reference to the connection and shut it down somewhere? This feels like it should be managed somewhere lower level in this deployment context.

#### Environment details

1. OS type and version: Windows -> Dataflow GCP
2. Java version: 1.8
3. Beam 1.28
4. pubsublite version(s): 
```    
<dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>pubsublite-beam-io</artifactId>
      <version>0.11.1</version>
    </dependency>
```

#### Steps to reproduce

  1. Create PubSubLit Subscriber in DataFlow Job

**Comment by GLStephen** [comment]
Possibly related. It seems that a Job using this library will never fully drain. It has to be canceled. That's a bit of a major roadblock for production deployments.

**Comment by dpcollins-google** [comment]
> I'm receiving the following error repeatedly.
Yeah this is a known issue. I think I know which channel this is, its going to be a bit difficult to fix.

> a Job using this library will never fully drain
This is more concerning. I'm going to reach out to the dataflow team and investigate this.

**Comment by dpcollins-google** [comment]
From Dataflow team, I've added the following text to the README. Unfortunately it looks like the v1 runner does not support drains with SplittableDoFns:

Only Dataflow runner v2 supports drain on PubsubLiteIO. Please contact dataflow customer support to request adding projects into the allowlist and launch the pipeline with --experiments=use_runner_v2. Using runner v2 requires 2.29.0 or above.

**Comment by dpcollins-google** [comment]
Follow up from dataflow team to edit to the following:

NOTE: Drain is not currently supported on PubsubLiteIO. Once Beam 2.29.0 is released, this will be supported
only when --experiments=use_runner_v2 is enabled. Please contact dataflow customer support to request adding projects
into the allowlist and launch the pipeline with --experiments=use_runner_v2.

**Comment by GLStephen** [comment]
@dpcollins-google I appreciate the info, working on getting on that whitelist now
