### ISSUE TITLE
Do you have a plan to release version 1.0 (after stabilizing APIs)?

### ISSUE THREAD

**Issue by suztomo** [googleapis/java-pubsublite#604]
This is not an urgent request. In general it's nice to stabilize APIs and release version 1.0 of a library. Apache Beam (Cloud Dataflow) and Spring Cloud GCP use the [Libraries BOM](https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM) to set most of Google Cloud libraries but the BOM currently does not have google-cloud-pubsublite. The Libraries BOM imports google-cloud-bom. Google-cloud-bom maintainers (@chingor13 ) prefer to have stable (post 1.0 release) libraries in it.

**Describe the solution you'd like**

Stabilize the APIs and release version 1.0.0. Then notify google-cloud-bom maintainers to include this google-cloud-pubsublite library.

**Describe alternatives you've considered**

Currently users specify the version of google-cloud-pubsublite independent from the Libraries BOM.

**Comment by anguillanneuf** [comment]
@suztomo Yes, we have considered marking this library as "stable". 

The only thing I'm unsure about is the inclusion of `pubsublite-beam-io`. Best if we wait for the [I/O released with Apache Beam](https://beam.apache.org/releases/javadoc/2.28.0/org/apache/beam/sdk/io/gcp/pubsublite/package-summary.html) to be stable first, then delete the one here, and then go for GA. 

Also tracking in: https://issues.apache.org/jira/browse/BEAM-10114

**Comment by suztomo** [comment]
Thank you for response. Looking forward.

Small feedback on API design: I found awkwardness in addDefaultMetadata static method:
https://github.com/apache/beam/pull/14578/files#r619328009 (@dpcollins-google helped me there)

**Comment by dpcollins-google** [comment]
I'd note in particular that that method is part of the internal API surface, and will not be stable even after a 1.0.0.

**Comment by anguillanneuf** [comment]
@suztomo Release 1.0.0 went out yesterday.
