### ISSUE TITLE
Need a more obvious way to set event time in a message

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/java-pubsublite#856]
`EventTime` is useful in deciding when to advance high watermarks for streaming engines (Beam/Spark/Flink). Right now to set event time in a message published to Pub/Sub Lite, one needs to use a custom attribute of key "x-goog-pubsublite-event-time-timestamp-proto" and pass in a string using `MessageTransforms.encodeAttributeEventTime()`:

```java
import com.google.cloud.pubsublite.cloudpubsub.MessageTransforms;

// ..

    String eventTime = MessageTransforms
        .encodeAttributeEventTime(Timestamp.newBuilder().setSeconds(100).build());

    ByteString data = ByteString.copyFromUtf8(message);

    PubsubMessage pubsubMessage =
        PubsubMessage.newBuilder()
            .setData(data)
            .putAttributes("x-goog-pubsublite-event-time-timestamp-proto", eventTime)
            .build();

    ApiFuture<String> future = publisher.publish(pubsubMessage);
```

Is there a better way to surface `EventTime` from the protos?

https://github.com/googleapis/java-pubsublite/blob/343afbffc2be92cb6be2670ef3ec34c599cd95dc/proto-google-cloud-pubsublite-v1/src/main/java/com/google/cloud/pubsublite/proto/PubSubMessageOrBuilder.java#L114-L144

**Comment by dpcollins-google** [comment]
The attribute key is `MessageTransforms.PUBSUB_LITE_EVENT_TIME_TIMESTAMP_PROTO` which is public. Is this insufficient?

**Comment by anguillanneuf** [comment]
Ideally, we should have `.setEventTime()` that accepts a `Timestamp` type.
