### ISSUE TITLE
Subscriber becoming stall after GC pause

### ISSUE THREAD

**Issue by gpoulin-hopper** [googleapis/java-pubsublite#871]
Some of are `Subscriber`s are becoming stalled (not receiving any new messages) without anything being logged even though they don't have any outstanding messages (`ack` was called for every messages received). Looking at logs, it seems that the partition that were last assigned to the stalled `Subscriber` are reassigned to other `Subscriber`. Looking at our metrics, there seems to be a correlation between `Subscriber` becoming stall and spike in GC.

Based on that info, it seems like the client fails some kind of heartbeat due to GC and the Pub/Sub Lite mark this client as dead, which is a reasonable behaviour. However, I would expect the `AssigningSubscriber` to detect this issue and treat it as a permanent error (close all services and notify `Listener`s of the failure).

**Comment by dpcollins-google** [comment]
Hello,

Thank you for your report. This should not be happening, and I will attempt to recreate and debug.

-Daniel

**Comment by dpcollins-google** [comment]
Going to close for now as not reproducible, as I have been unable to trigger this state. Please reopen in the future if you have more information, per out of band discussion.
